from __future__ import annotations

from pathlib import Path
from typing import Any


COLORS = {
    "Catalyst quantum attention": "#0f766e",
    "Scaled dot-product softmax": "#4f46e5",
}


def _svg_bar_chart(
    path: Path,
    *,
    title: str,
    ylabel: str,
    groups: list[str],
    series: dict[str, list[float]],
    suffix: str = "",
    lower_is_better: bool = False,
) -> None:
    width = 980
    height = 560
    left = 86
    right = 32
    top = 72
    bottom = 96
    plot_w = width - left - right
    plot_h = height - top - bottom
    max_value = max(max(values) for values in series.values()) or 1.0
    y_max = max_value * 1.18
    names = list(series.keys())
    group_w = plot_w / max(1, len(groups))
    bar_w = min(54, group_w / (len(names) + 1.2))

    def x_for(group_index: int, series_index: int) -> float:
        start = left + group_index * group_w + group_w / 2
        offset = (series_index - (len(names) - 1) / 2) * (bar_w + 8)
        return start + offset - bar_w / 2

    def y_for(value: float) -> float:
        return top + plot_h - (value / y_max) * plot_h

    parts = [
        '<svg xmlns="http://www.w3.org/2000/svg" width="980" height="560" viewBox="0 0 980 560">',
        "<style>",
        ".title{font:700 24px system-ui,sans-serif;fill:#111827}",
        ".label{font:600 13px system-ui,sans-serif;fill:#374151}",
        ".tick{font:12px system-ui,sans-serif;fill:#6b7280}",
        ".legend{font:13px system-ui,sans-serif;fill:#374151}",
        ".note{font:12px system-ui,sans-serif;fill:#6b7280}",
        "</style>",
        '<rect x="0" y="0" width="980" height="560" fill="#ffffff"/>',
        f'<text x="{left}" y="42" class="title">{title}</text>',
        f'<text x="24" y="{top + plot_h / 2}" transform="rotate(-90 24 {top + plot_h / 2})" class="label">{ylabel}</text>',
        f'<line x1="{left}" y1="{top + plot_h}" x2="{left + plot_w}" y2="{top + plot_h}" stroke="#d1d5db"/>',
        f'<line x1="{left}" y1="{top}" x2="{left}" y2="{top + plot_h}" stroke="#d1d5db"/>',
    ]
    for index in range(5):
        value = y_max * index / 4
        y = y_for(value)
        parts.append(f'<line x1="{left}" y1="{y:.2f}" x2="{left + plot_w}" y2="{y:.2f}" stroke="#eef2f7"/>')
        parts.append(f'<text x="{left - 10}" y="{y + 4:.2f}" text-anchor="end" class="tick">{value:.1f}{suffix}</text>')

    for group_index, group in enumerate(groups):
        center = left + group_index * group_w + group_w / 2
        parts.append(f'<text x="{center:.2f}" y="{height - 44}" text-anchor="middle" class="tick">{group}</text>')
        for series_index, name in enumerate(names):
            value = series[name][group_index]
            x = x_for(group_index, series_index)
            y = y_for(value)
            h = top + plot_h - y
            parts.append(
                f'<rect x="{x:.2f}" y="{y:.2f}" width="{bar_w:.2f}" height="{h:.2f}" rx="3" fill="{COLORS.get(name, "#111827")}"/>'
            )
            parts.append(
                f'<text x="{x + bar_w / 2:.2f}" y="{max(top + 14, y - 8):.2f}" text-anchor="middle" class="tick">{value:.1f}{suffix}</text>'
            )

    legend_x = left + plot_w - 260
    for index, name in enumerate(names):
        y = 36 + index * 22
        parts.append(f'<rect x="{legend_x}" y="{y - 11}" width="12" height="12" fill="{COLORS.get(name, "#111827")}"/>')
        parts.append(f'<text x="{legend_x + 20}" y="{y}" class="legend">{name}</text>')
    direction = "Lower is better." if lower_is_better else "Higher is better."
    parts.append(f'<text x="{left}" y="{height - 16}" class="note">{direction} Generated by catalyst-attention-adapter.</text>')
    parts.append("</svg>")
    path.write_text("\n".join(parts) + "\n", encoding="utf-8")


def write_charts(results: dict[str, Any], *, out_dir: str | Path = "charts") -> None:
    path = Path(out_dir)
    path.mkdir(parents=True, exist_ok=True)
    rows = results["attention"]
    groups = []
    for row in rows:
        label = f"{row['dimension']}d / {row['key_count']} keys"
        if label not in groups:
            groups.append(label)

    def grouped(metric: str) -> dict[str, list[float]]:
        out: dict[str, list[float]] = {}
        for row in rows:
            out.setdefault(row["method"], []).append(float(row[metric]))
        return out

    _svg_bar_chart(
        path / "attention_latency.svg",
        title="Catalyst Quantum Attention vs Softmax Latency",
        ylabel="Median microseconds",
        groups=groups,
        series=grouped("median_us"),
        suffix="",
        lower_is_better=True,
    )
    _svg_bar_chart(
        path / "attention_accuracy.svg",
        title="Catalyst Quantum Attention vs Softmax Accuracy",
        ylabel="Top-1 accuracy",
        groups=groups,
        series=grouped("top1_accuracy_pct"),
        suffix="%",
    )
    catalyst_speedups = [
        float(row["latency_vs_softmax_x"]) for row in rows if row["method"] == "Catalyst quantum attention"
    ]
    _svg_bar_chart(
        path / "attention_speedup.svg",
        title="Catalyst Quantum Attention Speedup vs Softmax",
        ylabel="Speedup multiple",
        groups=groups,
        series={"Catalyst quantum attention": catalyst_speedups},
        suffix="x",
    )
